// Code generated by Slice Machine. DO NOT EDIT.

import AllInOne from './AllInOne';
import Carrousel from './Carrousel';
import GetinTouch from './GetinTouch';
import TestSlice from './TestSlice';

export {
	AllInOne,
	Carrousel,
	GetinTouch,
	TestSlice,
};

export const components = {
	all_in_one: AllInOne,
	carrousel: Carrousel,
	first_bloc: GetinTouch,
	test_slice: TestSlice,
};
