import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { createClient } from "../prismicio";
import { SliceZone } from "@prismicio/react";
import { components } from "../slices";

export default function Home({ page }) {
  console.log(page);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SliceZone
          slices={page.data.slices}
          components={components}
        ></SliceZone>
      </main>
    </>
  );
}

export async function getStaticProps({ previewData }) {
  const client = createClient({ previewData });

  const page = await client.getByUID("homepage", "main");
  return {
    props: {
      page,
    },
  };
}
